version: '2'
#service that will run
services:
  jenkins:
  #its pulling Jenkins image
    image: jenkins/jenkins:lts
    #ports to expose 
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
      #volues to mount
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      #service posgres
  postgres:
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - /var/postgres-data:/var/lib/postgresql/data
      #service to run 
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
      #enviroment variables 
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
      #we need a postgres first so depends on is used
    depends_on: 
      - postgres

networks:
  jenkins:

